### ISSUE TITLE
Type Pirating Distances.jl

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#100]
I would be fine with adding it for now, but maybe let's open an issue so we don't forget it and fix it in case the upstream response is negative or the upstream changes take too long.

_Originally posted by @devmotion in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQxNTEzODc4OA==/comments/review_comment_

**Comment by st--** [comment]
It's not clear (to someone not familiar with the original context) what this is about, and the link does not seem to work for me, would it be sensible to clarify this issue a bit ?

**Comment by willtebbutt** [comment]
This was originally about whether or not we added some functionality to `Distances` that we needed inside this package or do things properly (I think it was probably something like implementing `pairwise(::SqEuclidean, ::AbstractVector)` or something that hadn't been implemented in `Distances` but seemed very reasonable.

In the end, we opted to just roll our own functions that default to calling `Distances.jl`'s functions, but gives us the flexibility to add the functionality we need.

@theogf @devmotion is this a fair summary? I'm a bit on the details because it all happened a while ago.

**Comment by devmotion** [comment]
I think that's it pretty much. It seems this issue could be closed? IIRC there are some other open issues related to `metric` such as e.g. fixing the name to something more appropriate such as `binary_op` but this specific issue seems to be resolved by using Distances only as fallback.

**Comment by willtebbutt** [comment]
Agreed. I'll close. Anyone should re-open if they feel there's more to be discussed.
