### ISSUE TITLE
Using a SimpleKernel on a vector of vector will fail

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#115]
MWE : 
```julia
A = fill(rand(3), 2)
k = SqExponentialKernel()
kernelmatrix(k, A) # Tries to call pairwise
```

**Comment by devmotion** [comment]
> A = fill(rand(3), 2)

Just a minor unrelated comment: `rand(3)` will be called only once, and the two entries of the vector of vectors that's created here will point to the result of that call, and hence reference exactly the same array. I guess usually that's not what's desired.

**Comment by theogf** [comment]
Yeah I know :) 
It's just quicker to make an array of array :stuck_out_tongue:

**Comment by theogf** [comment]
I have already been bitten pretty hard by `fill` so I learned my lesson :)

**Comment by willtebbutt** [comment]
Is this potentially something that we actually do want to error? My suspicion is that this is always going to be a bad slow fallback for a method where you pack your data into a `ColVecs` or `RowVecs`, so it might actually be a good thing that it errors?

**Comment by theogf** [comment]
I think this is a bad thing because even though what you need to compute is a `SimpleKernel` the data might be actually very complicated and only turns into vectors of real at the end after a series of transform (one could imagine a Deep Kernel for instance)

**Comment by theogf** [comment]
Also the fact that it errors only come from the fact that `Distances.jl` refuses to take arrays of arrays... See https://github.com/JuliaStats/Distances.jl/issues/152

**Comment by willtebbutt** [comment]
> I think this is a bad thing because even though what you need to compute is a SimpleKernel the data might be actually very complicated and only turns into vectors of real at the end after a series of transform (one could imagine a Deep Kernel for instance)

This isn't clear to me. Could you elaborate a little with an example?

**Comment by theogf** [comment]
Say I want to make a kernel evaluated on graphs for instance. I can create a Transform which will take a Graph object and turn it into a vector of reals. Now if I do this my vector of Graph will become a vector of vectors and I will be unable to use it with any SimpleKernel

**Comment by willtebbutt** [comment]
Hmmm yeah, good point. On the other hand you would ideally gather the individual vectors into a `ColVecs`. I wonder if there's a general mechanism that we could design for doing that...

**Comment by devmotion** [comment]
Maybe we should just implement our own `pairwise` and `pairwise!` function (that use `Distances.pairwise` and `Distances.pairwise!` as fallback) to be able to handle the case of vector of vectors and remove the type piracy in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/b10684d84b2063bd053c3eeb929b67d66c00d64b/src/generic.jl#L25-L48 (seems there's no response to @willtebbutt's question in Distances yet).

**Comment by willtebbutt** [comment]
I would have no objection to that proposal.

**Comment by theogf** [comment]
I also like your proposal! One can later propose to get this integrated to Distances.jl (more generally then what @willtebbutt proposes in https://github.com/JuliaStats/Distances.jl/issues/165
