### ISSUE TITLE
Feature Request: Adding PowerKernel

### ISSUE THREAD

**Issue by tirthasheshpatel** [JuliaGaussianProcesses/KernelFunctions.jl#131]
### Feature

A kernel can be exponentiated with a scalar using something like `^` symbol in Julia. AFAIK, there is no direct way to do this in `KernelFunctions.jl`.

### Expected Behaviour

It would be nice to see a `PowerKernel` with which I can do something like:

```julia
k = PeriodicKernel()
p = 2.

k = k ^ p
# or equivalently
k = PowerKernel(k, p)
```

### Current Workaround

```julia
k = PeriodicKernel()
p = 2.

x = randn(3)

cov = kernelmatrix(x) ^ p

# Another option is to multiple the kernel with itself `p` times
# This may be slow...
k = prod(fill(PeriodicKernel(), p))
```

**Comment by theogf** [comment]
Just to be clear, you don't want to apply the kernels element-wise?
But anyway I suppose this is feasibl.
The real workaround would be to do
```
k = prod(fill(PeriodicKernel(), 2))
```
but it would be computationally very inefficient.
I am just curious, what usecase do you have for this?

**Comment by tirthasheshpatel** [comment]
> Just to be clear, you don't want to apply the kernels element-wise?

Oh sorry! You are right. I wanted to multiply element wise...

> I am just curious, what usecase do you have for this?

I am just playing around with some GP frameworks and don't have a particular use case for this feature. I can close this if it is not very important enough to go in this package...

**Comment by theogf** [comment]
Ok then what you want to use is already existing and is `TensorProduct`. And the `^` notation would be an inappropriate one here!

**Comment by tirthasheshpatel** [comment]
Oh alright. I see how would one exponentiate the kernel with a scalar using `TensorProduct` kernel. Thanks for the help!
