### ISSUE TITLE
Make validate_dims opt-in

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#139]
`validate_dims` is slightly too aggressive at the minute. In particular, enforcing that the `dim` of each input is the same is expensive to check in general (e.g. to validate this properly you would need to check the length of each element of a `Vector{Vector{Float64}}`) and really just incorrect (e.g. string kernels can compare between strings of different lengths / dimensions) so it doesn't make sense to enforce this in general.

I propose instead to add a default implementation of `validate_dims` that doesn't error by default, i.e.
`validate_dims(x::AbstractVector, y::AbstractVector) = nothing`.

Then for any particular type we can offer it as an interface that you can implement if you want to be able to provide an informative error message.

It might also make sense to rename it to `validate_inputs` and generalise the idea slightly.

The `validate_inplace_dims` implementation, however, does make sense and does appear to be correct -- we really do want to make sure that the inputs are the correct length for the results to be stored in a matrix of the size of the one provided.

@theogf @devmotion @sharanry what are your thoughts?

**Comment by theogf** [comment]
I fully approve! That's also what I kinda proposed in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/138#discussion_r459352030

**Comment by willtebbutt** [comment]
Excellent. Once #138 is in I'll make the changes.

I think it's fine to view this particular piece of infrastructure as something that _hopefully_ catches errors, but isn't guaranteed to in all cases.

**Comment by theogf** [comment]
Solved by #147
