### ISSUE TITLE
Removing `BaseKernel`

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#149]
I am not sure what changed, but now `BaseKernel` has no reason to exist apparently. Doing a search on where it is used shows it clearly. I think we can also drop these deprecated methods:

https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/86cde328efdf162371bef45334feb10f3c05a363/src/generic.jl#L14-L18

The only question is : Are we replacing `SimpleKernel` by `BaseKernel` for kernels using `Distances.jl` or are we keeping `SimpleKernel` and simply remove `BaseKernel` ?

**Comment by willtebbutt** [comment]
I can't see a reason to keep `BaseKernel`.

**Comment by theogf** [comment]
Solved by #150
