### ISSUE TITLE
Exporting ColVecs, RowVecs and vec_of_vecs

### ISSUE THREAD

**Issue by sharanry** [JuliaGaussianProcesses/KernelFunctions.jl#163]
Shouldn't ColVecs, RowVecs and vec_of_vecs be available to the users? If we are to promote the use of these abstractions, I think it is prudent we export them.

**Comment by willtebbutt** [comment]
Absolutely. We've also not properly documented their use. A PR that both exports them and makes documentation on the matter visible to users would be great.

**Comment by codeboy5** [comment]
Hey I would like to take up this issue .
Any tips on how should I proceed ?

**Comment by theogf** [comment]
Hi @codeboy5 , thanks for contributing!
For solving this issue you should open a PR where you add the export to the forementioned types/methods and write detailed docs about what they are doing/how to use them.

**Comment by st--** [comment]
Should also address this comment: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/213#discussion_r553543552

**Comment by st--** [comment]
Should also add a docstring for `defaultobs` and remove the hard-coded constant from the docs (see https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/232/files#r559398795)

**Comment by devmotion** [comment]
No, as I wrote in the comment, I disagree. In my opinion there is no need for a docstring since it is an internal detail that is irrelevant for users. It is only relevant that by default columns are observations.

**Comment by theogf** [comment]
Solved in #159
