### ISSUE TITLE
Conditioning Euclidean distance

### ISSUE THREAD

**Issue by molet** [JuliaGaussianProcesses/KernelFunctions.jl#166]
Differentiating through Euclidean distance works well when full covariance matrix is computed:
```julia
using KernelFunctions
using Random
using Zygote

rng = MersenneTwister(1983)
x = rand(rng, 1, 10)

k_se(θ) = TransformedKernel(SEKernel(), ScaleTransform(θ))
k_exp(θ) = TransformedKernel(ExponentialKernel(), ScaleTransform(θ))
θ = 2.0

for k in [k_se, k_exp]
    obj(θ) = sum(kernelmatrix(k(θ), x; obsdim = 2))
    println((obj(θ), Zygote.gradient(obj, θ)))
end
(67.38225580906727, (-18.52555899516926,))
(61.50240059927843, (-12.128600317452783,))
```

However, for a single sample (`x'`) that is also present in `x` the derivative results in a `NaN`:
```julia
for k in [k_se, k_exp]
    obj(θ) = sum(kernelmatrix(k(θ), x, x[:, 1:1]; obsdim = 2))
    println((obj(θ), Zygote.gradient(obj, θ)))
end
(7.721890314421589, (-1.5014503825650642,))
(6.973839902317901, (NaN,))
```
This is very likely because in the latter case when distance is computed as the square root of the squared Euclidean norm there is no conditioning and therefore in the gradient a division by 0 appears.

**Comment by willtebbutt** [comment]
Yeah, this is definitely a Zygote-specific thing, but I've seen it a few times recently, so we should probably try and resolve it. I'm trying to figure out how to fix it at the minute.

**Comment by theogf** [comment]
This should be now fixed
