### ISSUE TITLE
RationalQuadraticKernel and GammaRationalQuadraticKernel implementations

### ISSUE THREAD

**Issue by molet** [JuliaGaussianProcesses/KernelFunctions.jl#170]
I would be interested if there is a particular reason of implementing `RationalQuadraticKernel` as:
```julia
κ(x,y)=(1+||x−y||²/α)^(-α)
```
instead of:
```julia
κ(x,y)=(1+||x−y||²/(2α))^(-α)
```
Most of the implementations I have seen are using the latter form and I'm wondering if `KernelFunctions.jl` could use it as well in order to make comparisons easier.

Also, this is the docstring of `GammaRationalQuadraticKernel`:
```julia
"""
`GammaRationalQuadraticKernel([ρ=1.0[,α=2.0[,γ=2.0]]])`
The Gamma-rational-quadratic kernel is an isotropic Mercer kernel given by the formula:

    κ(x,y)=(1+ρ^(2γ)||x−y||^(2γ)/α)^(-α)

where `α` is a shape parameter of the Euclidean distance and `γ` is another shape parameter.
"""
```
However, there is no such variable `ρ` that can be defined in the actual constructor:
```julia
struct GammaRationalQuadraticKernel{Tα<:Real, Tγ<:Real} <: SimpleKernel
    α::Vector{Tα}
    γ::Vector{Tγ}
    function GammaRationalQuadraticKernel(;alpha::Tα=2.0, gamma::Tγ=2.0, α::Tα=alpha, γ::Tγ=gamma) where {Tα<:Real, Tγ<:Real}
        @check_args(GammaRationalQuadraticKernel, α, α > one(Tα), "α > 1")
        @check_args(GammaRationalQuadraticKernel, γ, γ >= one(Tγ), "γ >= 1")
        return new{Tα, Tγ}([α], [γ])
    end
end
```
It might have been forgotten in the implementation or - if skipping it was intentional - it would be nice to update the docstring.

**Comment by willtebbutt** [comment]
> Most of the implementations I have seen are using the latter form and I'm wondering if KernelFunctions.jl could use it as well in order to make comparisons easier.

This probably relates to https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/158 -- I guess I just missed this when I was reviewing everything.

**Comment by devmotion** [comment]
This is fixed now: the definition of `RationalQuadraticKernel` was changed as suggested above and the docstring of `GammaRationalQuadraticKernel` (renamed to `GammaRationalKernel`) was fixed.
