### ISSUE TITLE
Piecewise Polynomial Kernel

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#177]
The `PiecewisePolynomialKernel` is something of an oddity in that our current implementation accepts an argument that parametrises a distance. While the dimensionality of this argument is needed so that we can ensure positive definiteness, the warping of the input space that it performs can be achieved via `transform`.

It would be great if someone could refactor this kernel for our next minor release (we might want to think about getting into the habit of maintaining a dev branch or something)

**Comment by devmotion** [comment]
It seems, similarly maybe the Mahalanobis kernel could be removed completely?
