### ISSUE TITLE
The new test utils fail due to precision

### ISSUE THREAD

**Issue by sharanry** [JuliaGaussianProcesses/KernelFunctions.jl#180]
1. The new test utils seems to cause some approximate equality tests to fail at random.

https://travis-ci.com/github/JuliaGaussianProcesses/KernelFunctions.jl/jobs/391803344#L431

2. They also seem to result in a negative value when it should be >=0. This causes an error with `sqrt` function.
https://travis-ci.com/github/JuliaGaussianProcesses/KernelFunctions.jl/jobs/391296729#L395

The first problem could probably be remedied by increasing the default `_ATOL` to something like `1e-5`. However, I am not sure if this is the right way to go about it.

I am not sure how to tackle the second problem.

**Comment by willtebbutt** [comment]
> The first problem could probably be remedied by increasing the default _ATOL to something like 1e-5. However, I am not sure if this is the right way to go about it.

Hmmm I would be more inclined to try and provide better guarantees about the spacing between examples to ensure stability rather than lower the tolerance. My guess is that a couple of points are too close together or something, and are causing numerical difficulties.

> They also seem to result in a negative value when it should be >=0. This causes an error with sqrt function.
https://travis-ci.com/github/JuliaGaussianProcesses/KernelFunctions.jl/jobs/391296729#L395

Yeah, I noticed this as well. I imagine that it would be solved by the same thing as the above, although I pointed out in #177 that this is a slightly odd implementation in any case, so we might be better off refactoring the kernel anyway.

**Comment by theogf** [comment]
>  I've never seen issues with negative values before with either the Euclidean or SqEuclidean distances.

Actually we did! But then I think it was solved by @devmotion  directly in Distances.jl

**Comment by willtebbutt** [comment]
> Actually we did! But then I think it was solved by @devmotion directly in Distances.jl

Ooooo interesting. Would be interesting to know if it's the same problem here.

**Comment by theogf** [comment]
It's mentionned here : https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/57#discussion_r400102519

**Comment by willtebbutt** [comment]
@devmotion looks like we have the same issue with the mahalanobis. Would the same fix likely work / would you be happy to open a PR that addresses it?

**Comment by devmotion** [comment]
It seems the same fix works, I opened a PR: https://github.com/JuliaStats/Distances.jl/pull/180

**Comment by devmotion** [comment]
The PR was merged and an update of Distances released, so at least the second error should be fixed.

**Comment by sharanry** [comment]
> Hmmm I would be more inclined to try and provide better guarantees about the spacing between examples to ensure stability rather than lower the tolerance. My guess is that a couple of points are too close together or something, and are causing numerical difficulties.

@willtebbutt 
We get the error when points are exactly same.

This is where the error occurs. Should we consider removing this test?
```julia
≈(kernelmatrix(k, x0), kernelmatrix(k, x0, x0), atol=atol)
```

**Comment by willtebbutt** [comment]
Hmmm no, I think this is quite an important test for consistency. I'll try and have a go at resolving this spacing issue today.

**Comment by devmotion** [comment]
It seems the tests were fixed (I am sure about the Distances.jl related one at least :stuck_out_tongue:). Please reopen if there is still something to do here.
