### ISSUE TITLE
Is it possible to make RBF Kernels?

### ISSUE THREAD

**Issue by kazucmpt** [JuliaGaussianProcesses/KernelFunctions.jl#191]
I would like to use RBF Kernels. That is,

k(x_i, x_j) = Exp[ -γ || x_i - x_j ||^2 ]

Do I have to use `KernelProduct` like it?

> k1 = SqExponentialKernel()
> k2 = ConstrantKernel(; c = exp( - gamma) )
> k_rbf = k1 * k2

**Comment by willtebbutt** [comment]
You can just write:
```julia
k = c * SqExponentialKernel()
```
:)

**Comment by kazucmpt** [comment]
Thank you for your quick response.
But I think `k = c * SqExponentialKernel()` is not equivalent with RBF Kernels.
The diagonal elements should be 0 because of the definition of RBF Kernel

![image](https://user-images.githubusercontent.com/25736044/99531181-b53f3480-29e5-11eb-80c7-841c13864a86.png)

**Comment by willtebbutt** [comment]
>  The diagonal elements should be 0 because of the definition of RBF Kernel

The RBF kernel is
```julia
k(x, y) = exp(-||x - y||^2)
```
(ignoring length scale and variance parameters for now). Consequently, the diagonal elements should be `1`, not `0`. Does this make sense?

**Comment by kazucmpt** [comment]
Oh, sorry. It was typo. The diagonal elements should be 1. 

I need variance parameters and this is why I asked it. 
I am looking forward to update!

Thank you !

**Comment by willtebbutt** [comment]
@kazucmpt no problem.

Ah, I see. I believe the parameter that you are referring to as "variance" is in fact the "inverse length scale". You can set this as follows:
```julia
transform(SqExponentialKernel(), 1 / γ)
```

Does this make sense?

**Comment by theogf** [comment]
> I would like to use RBF Kernels. That is,
> 
> k(x_i, x_j) = Exp[ -γ || x_i - x_j ||^2 ]
> 
> Do I have to use `KernelProduct` like it?
> 
> > k1 = SqExponentialKernel()
> > k2 = ConstrantKernel(; c = exp( - gamma) )
> > k_rbf = k1 * k2

If you want to get the exact same result as the formula you wrote this would be : 
```julia
k = transform(SqExponentialKernel(), sqrt(2γ))
```
