### ISSUE TITLE
setindex! for ColVecs

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#195]
I end up facing a problem where it would be convenient to have `setindex!` implemented for `ColVecs/RowVecs`. Since the underlying data object is a matrix, it should be possible to do it, and if not it would just error as one would expect. Any opinion on this? I would make a PR for it

**Comment by willtebbutt** [comment]
Do you want to set an entire column / row, or a single element of one of them? In the former case, I agree that it'll be straightforward, but I'm not sure how you would express the latter.

**Comment by willtebbutt** [comment]
Of course, we could formalise an interface to get the wrapped data and you just run `setindex!` on that 🤷

**Comment by theogf** [comment]
Yeah I meant replacing an entire column/row, something like:
```julia
A = rand(3,3)
C = ColVecs(A)
d = rand(3)
C[1] = d 
# same as 
A[:, 1] = d
```

**Comment by willtebbutt** [comment]
Yeah, that should be a 1-liner I reckon, and would definitely make sense. Happy to review a PR :)
