### ISSUE TITLE
Split API docs into separate pages, remove redundancy with kernels/transforms

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#216]
Maybe one could also just move the list of transforms here (the full API section is a bit overwhelming to be honest). But if we want to do this, it might best to change it in a separate PR and maybe for some other sections as well.

_Originally posted by @devmotion in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/213#discussion_r553648569_

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/236.
