### ISSUE TITLE
Consolidate mathematical description of kernels between docs and docstrings

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#218]
@willtebbutt wrote on #213:
> I'm concerned is that we're duplicating documentation a bit at the minute by having both docstrings and having the entire `Kernel`s section written out manually. This creates an opportunity for the docs to decouple from the docstrings and increases the maintenance burden. I wonder whether it would make sense, therefore, to consolidate this documentation -- if we were to move the concise mathematical description of the kernels from the docs to the docstrings, and just move /duplicate bits of the `API` section in the `Kernel Functions` section we could get the best of both worlds?

_Originally posted by @willtebbutt in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/213#issuecomment-757064536_

**Comment by devmotion** [comment]
This is basically what I had in mind with the suggestion in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/216 as well.

**Comment by devmotion** [comment]
Closed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/236.
