### ISSUE TITLE
CI: introduce automatic code formatting (e.g. JuliaFormatter)?

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#219]
In Python projects I've made very good experiences with automatic code formatting using `black`, and I was delighted to find Julia having similar packages such as https://github.com/domluna/JuliaFormatter.jl. Using an automatic code formatter tends to make code rather more readable (automatically breaking long statements etc., nice indentation, etc.), consistent, whilst at the same time removing any discussions around how to format code in PRs. What are your thoughts on introducing that in here? For that I would a) add a check to the CI that the code is consistent with the formatter, and b) make it easy (Makefile/script?) to format the code before pushing. It would also require a one-off PR to get the currently existing code formatted.

**Comment by devmotion** [comment]
Last time I checked JuliaFormatter didn't support [BlueStyle](https://github.com/invenia/BlueStyle), maybe this changed? BlueStyle is the code format we use in this repo (there's a badge in the README), currently this is enforced manually by reviewers.

**Comment by devmotion** [comment]
We also had a short discussion about JuliaFormatter a while ago, see e.g. https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/76#issuecomment-610997537.

**Comment by willtebbutt** [comment]
> Last time I checked JuliaFormatter didn't support BlueStyle, maybe this changed? BlueStyle is the code format we use in this repo (there's a badge in the README), currently this is enforced manually by reviewers.

This has indeed changed -- we should start utilising it. It's not perfect, but it does a reasonable job.

**Comment by nickrobinson251** [comment]
https://domluna.github.io/JuliaFormatter.jl/stable/blue_style/

**Comment by devmotion** [comment]
We could add e.g. something similar to https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml to check the format automatically. This could address point a) in the OP. I am not sure about suggestion b) - I guess it should be sufficient to add the JuliaFormatter config to the repo and point contributors to JuliaFormatter and the different plugins?

**Comment by st--** [comment]
You can see the changes due to running JuliaFormatter with style=blue in #220 - there's a few minor changes, but as far as I can tell they're all sensible changes/improvements. Let me know if you're happy with this, and I can add the .yml for including an explicit format check as part of the CI.
