### ISSUE TITLE
Rename kerneldiagmatrix ?

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#233]
`kerneldiagmatrix` seems a somewhat confusing choice of name - intuitively, I would expect this to still return a (`Diagonal`) matrix, not the vector of the diagonal. `kernelmatrixdiag` or `kernelmatrix_diag` would seem more intuitive: then `kernelmatrix(...) |> diag === kernelmatrixdiag(...)` and it would also be in line with `cov_diag` and `mean_and_cov_diag` in AbstractGP.jl. A backwards-compatible deprecation should be easy. I'd be happy to make a PR with these changes if you're generally in agreement. Thoughts?

**Comment by theogf** [comment]
`kernelmatrix_diag` sounds good to me.
