### ISSUE TITLE
Consolidating the linear transforms

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#237]
We presently have three different linear transforms that behave slightly differently:

1. ScaleTransform
2. ARDTransform
3. LinearTransform

While I can see the advantage of `ScaleTransform`, since it doesn't require one to know the dimensionality of the inputs when specifying the kernel, it seems to be that `ARDTransform` is a bit redundant -- would it not be more straightforward to implement it using a `LinearTransform` with a `Diagonal` matrix?

It's also a bit weird to call it `ARDTransform` -- the naming of the transforms ought to make sense in isolation from all of our kernels. `ARD` doesn't make sense to me outiside the context of models that involve kernels. Does anyone else feel that way about the name?

**Comment by devmotion** [comment]
Yes, I agree: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/107

I was also surprised to see that there exists an `ARDTransform(s::Real, dim::Integer)` constructor.

**Comment by willtebbutt** [comment]
Wow, I even commented on that issue. Closing in favour of #107
