### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#249]
E.g. https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/235/checks?check_run_id=1772621026

These seem to be numeric tests that occasionally don't `==` due to discrepancies amongst the least significant digits. Could be fixed by replacing with `≈`. Would that be the right solution? Happy to make a PR for that. It's a bit frustrating contributing PRs if they then keep failing for reasons unrelated to your changes...

**Comment by willtebbutt** [comment]
That would be great. I'm kind of surprised we've got an `==` test rather than an `isapprox` test. I agree regarding spurious test failures -- very annoying.

**Comment by st--** [comment]
Woops. I just realised I forgot the -b in the git checkout and didn't spot the error message - so I was still on `master` and pushed straight to that... @willtebbutt can you check that you are happy with the commit (9571eb0)? It's a very minor change - if you are happy, probably not worth the roll-back hassle and easier to just leave it...

**Comment by willtebbutt** [comment]
Haha no problem. Seems fine to me :)
