### ISSUE TITLE
Retire `kernelmatrix_diag(k, x, y)` for x≠y?

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#250]
> I haven't used `kerneldiagmat` in any downstream code but I would have assumed that the two argument version is more useful. For e.g. translation-invariant kernels `kerneldiagmat(k, x)` is just trivial and returns a constant vector (usually of ones for unscaled kernels)

In Gaussian process models it's exactly the `kernelmatrix_diag(k, x)` that's needed all the time - it may be trivial for stationary kernels (but also has the advantage it's super fast to compute), but it's also common to use non-stationary kernels (e.g. linear, arc-cosine, change-points).

> whereas `kerneldiagmat(k, x, y) = [k(xi, yi) for (xi, yi) in zip(x, y)]` is a more interesting non-constant vector.

In contrast, I've not come across any use-case for `kernelmatrix_diag(k, x, y)` with y!=x (but having to have the same length) which is why I asked.

If we can't think of any use-cases, would it not be better to save the maintenance cost? What's the value of keeping around functions just because we can write them if we have no use for it?

_Originally posted by @st-- in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/235#issuecomment-768312245_

**Comment by willtebbutt** [comment]
Yup. See [here](https://willtebbutt.github.io/Stheno.jl/dev/internals/#diag-methods-1) for a wordy explanation. I did have a good concrete example of this somewhere... will try and dig it up.

**Comment by devmotion** [comment]
It seems this issue can be closed then? (Updated link: https://juliagaussianprocesses.github.io/Stheno.jl/dev/internals/#diag-methods-1)
