### ISSUE TITLE
Having formatting done automatically

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#253]
I am very much not a fan of the formatting check. One cannot even know what's wrong with the current format. How about having automatic formatting PR instead?
See : https://github.com/julia-actions/julia-format
Here is a concrete example using BlueStyle : https://github.com/adrhill/NoiseRobustDifferentiation.jl/blob/main/.github/workflows/format_pr.yml

**Comment by devmotion** [comment]
I don't think this is correct? The configuration file (https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/.JuliaFormatter.toml) specifies that we use BlueStyle, therefore `format` should use BlueStyle automatically.

**Comment by theogf** [comment]
Oh I completely missed that, thanks for the pointer!

**Comment by theogf** [comment]
Closed by #260
