### ISSUE TITLE
Kernel matrix normalization

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGaussianProcesses/KernelFunctions.jl#259]
Would it make sense to have a kernel in this package that wraps another kernel and ensures that the matrix is normalized by calculating

```math
K'(x, y) = K(x, y) / sqrt(K(x, x), K(y, y))
```
? I think this might be helpful in cases of non-numeric input such as strings or graphs, where one cannot simply normalize the input features. For example, kernels in GraKeL have this option: <https://github.com/ysig/GraKeL/blob/3dc692a86a49542de7314c6d904d9d0afee9d196/grakel/kernels/kernel.py#L60>.
Although in GraKeL this is done by passing an rgument to the kernel constructor.

Also, here is some paper on that topic: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.83.2658&rep=rep1&type=pdf

**Comment by willtebbutt** [comment]
Hi @simonschoelly . I think this could make sense, although I've not come across these kernels before. Maybe @devmotion or @theogf have?

**Comment by willtebbutt** [comment]
Seem reasonable to me. @simonschoelly if you fancied opening a PR that implements this, I would be happy to review.

Probably best to take inspiration from how we implement [ScaledKernel](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/src/kernels/scaledkernel.jl), or one of the other kernels in that directory.

**Comment by theogf** [comment]
Actually wouldn't that be more efficient for `kernelmatrix(X, Y)` to do something like
```julia
function kernelmatrix(k::NormalizedKernel, X, Y)
	dX = inv.(sqrt.(kernelmatrix_diag(k.kernel, X)))
	dY = inv.(sqrt.(kernelmatrix_diag(k.kernel, Y)))
	K = kernelmatrix(k.kernel, X, Y)
	return dX .* K .* dY'
end
```
I am not sure about the return (needs to be checked) but just wanted to throw the idea.

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/274.
