### ISSUE TITLE
Add back `metric` in type for stationary kernels

### ISSUE THREAD

**Issue by torfjelde** [JuliaGaussianProcesses/KernelFunctions.jl#273]
## "Problem"
For a large set of kernels (all those based on `SimpleKernel`), we require a `metric` for their definition. At the moment the `metric` for a particular kernel is defined by `KernelFunctions.metric(::Kernel)` and is therefore *fixed* (at least the *type* of `metric` is fixed) for every implementation of a `Kernel`.

This means that if you want to use another `metric` in an already implemented kernel, say, `Matern12Kernel`, then you can take either of the following approaches:
1. Overload `KernelFunctions.metric(::Matern12Kernel) = MyMetric()`. This is of course a big no-no since it will change behavior in other packages using the `Mater12Kernel`.
2. Define your own kernel using `SimpleKernel`:
   ```julia
   struct MyMatern12Kernel <: SimpleKernel end
   KernelFunctions.metric(::MyMatern12Kernel) = MyMetric()
   kappa(::MyMatern12Kernel, d) = exp(-d)
   ```
   which, in fairness, isn't too hard.

## Improvement?
But an alternative would be to include the `metric` used in the kernel itself, e.g. adding an additional field to `Matern12Kernel` called `metric`, and allow specification of the `metric` via constructor. In fact this is what KernelFunctions.jl used to (though AFAIK in most cases you still couldn't actually use a different `mmetric` because it was hard-coded into the constructor). Then we could do
```julia
Matern12Kernel(nu, MyMetric())
```

Now, at this point it's completely fair to ask: "Tor, why do you need this?". As we all know, It is often said that software developers too often think "*Should* we do this?" rather than "*Can* we do this?". Or was it the other way around? Anyways, the point is that we should do this because _can_. 

I guess another good reason is also that we can easily define kernels on other spaces, e.g. `Matern12Kernel` on the sphere using but using the *geodesic* distance metric rather than standard Euclidean metric. The fun part is that this leads to different kernel spaces! It's worth pointing out that exchanging the metric in an existing kernel doens't necessarily lead to a valid metric, but there are several examples where it indeed does, e.g. as described in [1]. And there seems to be enough of them to IMO justify making the above design-choice.

You could then wonder "Why not just implement your own using `SimpleKernel` Tor? Are you lazy?". Yes, but it's besides the point. The annoying bit about a separate implementation for every `Kernel` + `metric` combination is that you'll end up with all these implementations spread across multiple packages. 

A couple of additional reasons:
1. Completely backwards compatible change, so IMO, beyond effort, the change doesn't cost much.
2. User-expectation. I was honestly suprised to find that I couldn't easily specify the metric (I wanted `Matern12Kernel` on S^2), but had to define a new on to get the desired behavior.

Worth pointing out that I'm not an expert on the topic of RKHSs and manifolds (only started looking at it recently), and so take what I say with a grain of salt. E.g. I don't as of yet have a full overview of how many kernels that are extendable in this manner (there's a really nice table in [1]). I'll hopefully have some time to do more reading on the topic next week, and I'll update this issue when I have a better overview (if the discussion is still ongoing).

## References
1. https://www.cv-foundation.org/openaccess/content_cvpr_2015/html/Feragen_Geodesic_Exponential_Kernels_2015_CVPR_paper.html

**Comment by devmotion** [comment]
Since I have some use cases where I work with exponential kernels with non-standard non-Euclidean metrics, I think a more flexible design would be convenient 🙂 However, I wonder if one could/should constrain it to reasonable/mathematically valid metrics in some way. It seems one idea was to base it on the considered manifold of inputs? If one would allow arbitrary metrics, then the Gaussian kernel would just be a special exponential kernel with SqEuclidean distance - however, if one would allow a specific metric for each manifold (e.g. adding a manifold type parameter or field to the kernel and then base `metric(...)` on it), this would not be possible. I am not completely sure which approach (or what alternative) would be superior.

> Completely backwards compatible change, so IMO, beyond effort, the change doesn't cost much.

Unfortunately, this is not the case. The types will change and hence it is a breaking change (e.g. it might break dispatches if e.g. Gaussian is suddenly not a concrete type anymore).

**Comment by torfjelde** [comment]
> Since I have some use cases where I work with exponential kernels with non-standard non-Euclidean metrics, I think a more flexible design would be convenient

Okay, so now I'm very curious what you're working on!

> However, I wonder if one could/should constrain it to reasonable/mathematically valid metrics in some way. It seems one idea was to base it on the considered manifold of inputs? If one would allow arbitrary metrics, then the Gaussian kernel would just be a special exponential kernel with SqEuclidean distance - however, if one would allow a specific metric for each manifold (e.g. adding a manifold type parameter or field to the kernel and then base `metric(...)` on it), this would not be possible. I am not completely sure which approach (or what alternative) would be superior.

I really struggle to see how we'll be able to cover all these cases. I also am of the opnion that *most* people that actively think about using a different metric for an existing kernel, will be aware that this can indeed be an issue.

There are also "weird" cases where what might seem like the wrong thing to do might not be, e.g. I bet there are cases where using, say, the exponential kernel on the *whole* space will lead to an "invalid" kernel, while restricting yourself to a compact subspace will be okay. It's going to be very difficult to cover this IMO in any reasonable way :confused:

> 
> > Completely backwards compatible change, so IMO, beyond effort, the change doesn't cost much.
> 
> Unfortunately, this is not the case. The types will change and hence it is a breaking change (e.g. it might break dispatches if e.g. Gaussian is suddenly not a concrete type anymore).

So I deliberately didn't mention this because it adds to the "cost" of making this change. IMO we should just add in the `metric` and then we can cosider a more major breaking change at a later stage, treating such a unification as a separate issue. It's indeed redundant, but at the same time it's very non-invasive.With that being said, I really like the unifcation:) Just think adding the `metric` field has sufficiently higher priority than unification, to the point where it's worth separating the issues.

**Comment by devmotion** [comment]
Actually, I didn't consider any unification in my comment on whether it is a breaking change. Just adding a `metric` field is already a breaking change - it changes the types (e.g. from `SqExponentialKernel` to `SqExponentialKernel{M}` where `M` is the type of the metric) such that existing concrete types become abstract (e.g. `SqExponentialKernel` is an abstract type then) which can break e.g. dispatches and Union types.

**Comment by torfjelde** [comment]
Aaah of course, thanks :+1: I was thinking that they were mostly abstract already because of kernel parameters, e.g. length scale, but forgot these are implemented as transforms for most of the cases.

**Comment by theogf** [comment]
One clueless question or maybe possible improvement.
If we start to have fields for some of the kernels they stop being Singleton types, wouldn't induce a loss in performance?
Alternatively we can simply parametrize the kernel `SimpleKernel{<:Tmetric}` without actually storing the metric? And therefore keep using the `metric` approach.

Overall I am also pretty positive for this change.

**Comment by devmotion** [comment]
Metrics can contain fields themselves (e.g. Mahalanobis distance) and therefore in general an instance is needed and a type parameter is not sufficient.
