### ISSUE TITLE
rename transform?

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#275]
Lots of packages export a function called transform, including this one and DataFrames. While this isn't inherently problematic, it is kind of annoying.

I wonder if there's another name that we could pick that's a bit less generic, and still reflects what's going on. I vaguely remember there being discussions abot this somewhere, but I can't find them now.

**Comment by theogf** [comment]
I think this was already mentioned in #217

**Comment by willtebbutt** [comment]
A, yes, right you are. I'll close this in favour of that.
