### ISSUE TITLE
Contructors for Kernels without kwargs

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#288]
I'm a fan of the new metrics fields in a number of the kernels, but it looks like most of the constructors have been implemented as kwarg methods, and are _inner_ constuctors.

Would anyone object to me making the kwarg constructors outer constructors? It just makes life easier when working with default implementations of`to_vec` etc. It don't think it should be breaking.

For example:
```julia
struct SqExponentialKernel{M} <: SimpleKernel
    metric::M

    function SqExponentialKernel(; metric=Euclidean())
        return new{typeof(metric)}(metric)
    end
end
```
would become
```julia
struct SqExponentialKernel{M} <: SimpleKernel
    metric::M
end
SqExponentialKernel(; metric=Euclidean()) = SqExponentialKernel(metric)
```

**Comment by devmotion** [comment]
I would be fine with it :+1:

**Comment by theogf** [comment]
Yeah that sounds good to me too!

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/289.
