### ISSUE TITLE
Parallelise tests in build

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#315]
> Currently the rest of the build takes ~40 minutes anyways so that shouldn't make it longer overall.

IMO this is a motivation for splitting the tests into different groups that are run in parallel (similar what we do in the SciML ecosystem: https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/runtests.jl) rather than running the examples in serial.

_Originally posted by @devmotion in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/303#issuecomment-870543998_

**Comment by 4aHxKzD** [comment]
Related to but a different issue is not being able to run sections of the tests separately through the command line. I`ve been thinking of implementing the code that allows to use a [`Pkg.Test` feature](https://github.com/JuliaLang/Pkg.jl/pull/1226) that was added for this purpose. I think with this potential contributors will have an easier time when experimenting stuff to add to the package.

**Comment by 4aHxKzD** [comment]
Maybe both ideas can be implemented at the same time?

**Comment by devmotion** [comment]
This is already part of my suggestion above. You would just set e.g. `ENV["GROUP"] = "BaseKernels"`.

**Comment by 4aHxKzD** [comment]
Oh that also works with comand line arguments?

**Comment by devmotion** [comment]
There are no command line arguments involved here. It is based on an environment variable that you can set in your shell before starting Julia or in the Julia REPL with `ENV[...] = ...` or `withenv(... => ...) do ....`.
