### ISSUE TITLE
Use dev in examples?

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#339]
Out examples each have a different environment, and each has it's own dependency on AbstractGPs. Currently, this dependency is not tied to the currently checked-out branch via `dev ../..` or whatever. I wonder whether we should do this?

Reasons in favour:
1. allows us to run the examples in CI to ensure that they still pass when we make changes.
1. it ensures that our examples run on whatever the most recent version of 
1. if we _do_ run our examples as part of CI, it'll give us a few examples of stuff running in the wild, which is extra coverage, which is probably a good thing

I also don't recall whether we've already had this conversation and ruled this out...

**Comment by devmotion** [comment]
The examples (or at least some of them) use the checked out development version: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/fbce558b9362fa7e6d4c810ec7a98de09f3990b8/examples/kernel-ridge-regression/Manifest.toml#L284

**Comment by willtebbutt** [comment]
Oh -- I extrapolated from a single data point! https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/fbce558b9362fa7e6d4c810ec7a98de09f3990b8/examples/gaussian-process-priors/Manifest.toml#L282

I'll make a PR to correct.
