### ISSUE TITLE
Add periodic kernels

### ISSUE THREAD

**Issue by IsakFalk** [JuliaGaussianProcesses/KernelFunctions.jl#34]
I was playing around with periodic data and noticed that the periodic kernel, a general form can be found in [this document, equation 47](http://www.inference.org.uk/mackay/gpB.pdf), isn't implemented.

I think you could use a transformation together with one of the existing kernels that yields this kernel, but it would be nice to have easy access to it.

**Comment by theogf** [comment]
Another possibility is to define a new metric `Periodic` and leave the `r_i` as parameters of the kernel.
