### ISSUE TITLE
Tensor product with Select transform

### ISSUE THREAD

**Issue by kescobo** [JuliaGaussianProcesses/KernelFunctions.jl#351]
It would be useful to be able to be able to build up GPs by combining different individually-generated ones. One barrier is with KernelTensorProducts that are made up of individual elements with `SelectTransform`. In other words, this works:

```
x1 = 1:20
x2 = randn(20)

k1 = SqExponentialKernel()
k2 = LinearKernel()

K = (k1 ⊗ k2) ∘ SelectTransform([1,2])
pr1 = AbstractGPs.FiniteGP(GP(K), hcat(x1,x2), obsdim=1)
rand(pr1)
```

But this does not:

```
K = (k1 ∘ SelectTransform([1])) ⊗ (k2 ∘ SelectTransform([2]))
pr2 = AbstractGPs.FiniteGP(GP(K), hcat(x1,x2), obsdim=1)
rand(pr2)
```

The error is `ERROR: MethodError: no method matching (::SelectTransform{Vector{Int64}})(::Float64)`

**Comment by willtebbutt** [comment]
Hi @kescobo . Thanks for opening this issue.

I suspect I'm missing your point, because AFAICT your second example could be implemented as
```julia
K = k1 ⊗ k2
pr2 = AbstractGPs.FiniteGP(GP(K), hcat(x1,x2), obsdim=1)
rand(pr2)
```
Is this not what you're after?

**Comment by kescobo** [comment]
In my actual  situation, I'm also including kernel addition, and I want to act element-wise (see [this discussion](https://julialang.zulipchat.com/#narrow/stream/234072-probprog/topic/Something.20like.20.22Random.20Effects.20Kernel.22.20in.20a.20FiniteGP.3F/near/247352489) on zulip for more info).

So eg I have `k1 ⊗ k2 + k3` and I want `k1 ⊗ k2` to act on the first two columns of my input, and `k3` to act on the third column. But I'm trying to build up the kernel in a procedural way, so it would be much easier to have eg `k1` associated with column 1, and `k2` associated with column 2 etc, and then be able to compose them with `k1 ⊗ k2` and have the select transform propagate. Does that make sense?

Note: it's entirely possible I misunderstand something fundamental about this...

**Comment by willtebbutt** [comment]
Ahh I see. I wonder whether you don't actually need the tensor product then, and could just use regular kernel sums, products, and the `SelectTransform`. Something like
```julia
k1 = SEKernel() ∘ SelectTransform([1])
k2 = LinearKernel() ∘ SelectTransform([2])
k3 = SEKernel() ∘ SelectTransform([3])
k = k1 * k2 + k3

x = ColVecs(randn(3, 20))
rand(GP(k)(x))
```
perhaps?

**Comment by kescobo** [comment]
Hmm - that seems to give me the exact same answer, so I can definitely use that.

It's possible I don't know what a tensor product (as opposed to a regular product) is :flushed:

**Comment by willtebbutt** [comment]
Well a manual implementation of the tensor product kernel would be something like
```julia
k1 = SEKernel() ∘ SelectTransform([1])
k2 = LinearKernel() ∘ SelectTransform([2])
k = k1 * k2
```
for two inputs, so I don't think your intuition is off :)
