### ISSUE TITLE
Adding Cancel action to PkgTemplates.jl

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#355]
The Cancel.yml action is great. It would be nice to make it trivial to employ in new repos. It would be great if it were a plugin in [PkgTemplates.jl](https://github.com/invenia/PkgTemplates.jl/).

**Comment by devmotion** [comment]
It seems this can be closed now since we removed the Cancel action again. It might still be useful to add the `concurrency` settings to the PkgTemplates template.
