### ISSUE TITLE
Force some parameters to be Floats

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#361]
Just faced a stupid issue where because I would define a kernel as
```
k = 2 * SqExponentialKernel() \circ ScaleTransform(2.0)
```
optimisation on the `2` would of course fail. Should we enforce conversion to `Float` to avoid that or leave it to the user to find out?

**Comment by devmotion** [comment]
I think we should not enforce it, mainly because the promotion might be even more surprising and can cause issues that would be difficult to spot (e.g., when working with GPUs probably you would want `Float32` and promotion to `Float64` might slow down your computations).

**Comment by theogf** [comment]
Maybe a @warn with max log=1?

**Comment by devmotion** [comment]
I am not sure - it's completely fine to use an integer-valued parameter if you don't want to optimize it (and it is even fine if you optimize only on the space of natural numbers :smile:).

**Comment by theogf** [comment]
Yeah fair enough, I just got bitten by it so I thought preventing it for other people would be cool. But you're right, it just brings too many complications...
