### ISSUE TITLE
Zygote 0.6.30 broke `@inferred` test in check_zygote_type_stability

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#410]
Work-around in #409, but we've got to manually keep track of this issue as the `@test_broken` won't let us know if/when the type check passes again.

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/409/commits/b135c7abc112d419db0451f87470256e859e9653.
