### ISSUE TITLE
Delta type restrictions

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#479]
@theogf do you know why our `Delta` metric is constrained to work for numeric-ish types? Should it not work for anything that has `==` defined on it?

cc @glennmoy

**Comment by theogf** [comment]
Yeah no idea why I did this... This should be changed...

**Comment by willtebbutt** [comment]
Cool. We should add a test when we do. I think we should probably do a more general audit, but we shouldn't block this change in the short-term.

@molet do you have any other examples of kernels where you'd have thought things should just work out-of-the-box with non-numeric data types and they don't?

**Comment by glennmoy** [comment]
`_wrap` is another example (where we initially came across this)

Restricted to `AbstractVector{<:Real}` and `AbstractMatrix{<:Real}`

https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/d425983cd734c5c9c2e8c7573a97491ea5ecaa52/src/transform/selecttransform.jl#L31-L32

**Comment by molet** [comment]
Although there might be some exceptions like kernels in `constant.jl`, I think in general it is a good approach to require numeric types for most of the kernels.

So far, I successfully used `FunctionTransform` for many situations when I needed to convert a non-numeric type to a numeric one to be able to use specific numeric type based kernels. I think this is a good practice.

Therefore, I would rather focus on making some transform functions more general and let them take non-numerical types: `SelectTransform` and `FunctionTransform` would definitely need this feature (so we might want to change this [line](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/master/src/transform/functiontransform.jl#L26) as well to be more general).

**Comment by glennmoy** [comment]
> Although there might be some exceptions like kernels in `constant.jl`, I think in general it is a good approach to require numeric types for most of the kernels.

If this is the desired interface it would be good to document it.

**Comment by theogf** [comment]
> Although there might be some exceptions like kernels in constant.jl, I think in general it is a good approach to require numeric types for most of the kernels.

I think that's already true with the `kappa` function. But for things like `Transform` and `Metric` types, this should not be the case. We aim at being as agnostic as possible to the type of data.

**Comment by willtebbutt** [comment]
I believe that this has been resolved via #480  so will close this issue. Please let me know if there's anything missing.
