### ISSUE TITLE
Does it make sense to replace custom ColVecs, RowVecs code with ArraysOfArrays library

### ISSUE THREAD

**Issue by FelixBenning** [JuliaGaussianProcesses/KernelFunctions.jl#516]
see https://juliaarrays.github.io/ArraysOfArrays.jl/stable/. This appears to do the same thing. Just more general. This would allow more than matrices to be passed. I.e. you could have more than 1-dimensional input vectors.

**Comment by willtebbutt** [comment]
It's an option. Taking a look at the code, the implementation looks reasonably complicated in comparison to our `ColVecs` / `RowVecs`, which makes me reluctant to adopt it.

That being said, there's nothing to stop you writing an extension to `KernelFunctions` which directly extends our kernels to interoperate nicely with those from `ArrayOfArrays.jl`, without us removing `ColVecs` / `RowVecs`.

**Comment by devmotion** [comment]
IIRC the idea (a while back) was rather to use `eachrow` and `eachcol` since starting from Julia 1.9 (?) they return an array and not an iterator anymore: https://github.com/JuliaLang/julia/pull/32310

**Comment by devmotion** [comment]
See eg https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/394#issuecomment-956440820

**Comment by FelixBenning** [comment]
ah right `eachrow` and `eachcol` seems like the best solution
