### ISSUE TITLE
Get rid of `_kernel`

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#72]
It is not really clear what the use of `_kernel` is and it seems to overlap with `kappa`. Should we just get rid of it ?

**Comment by willtebbutt** [comment]
I didn't think that `kappa` was defined for all kernels? eg. non `BaseKernel`s. I have no idea what `_kernel` does though 🤷‍♂️

**Comment by devmotion** [comment]
Was fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/95.
