### ISSUE TITLE
Using mapslices for FunctionTransform make it incompatible with Zygote

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#74]
And 1 point for @willtebbutt's `RowVec` 
For now the more immediate solution would be to switch between `eachrow` and `eachcol` ...

**Comment by devmotion** [comment]
AFAICT this was fixed in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/152.
