### ISSUE TITLE
Split packages between methods and collection of kernels

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#86]
I am not sure how much sense it makes. But should we split this package by creating a `AbstractKernels.jl` package where all the kernelmatrix and generic functions are and keep this one as a library of kernels? This would avoid conflict in the different PRs

**Comment by willtebbutt** [comment]
I'm not in favour of this. I can see the rationale for avoiding conflicts between PRs, but we're currently going through a period where _loads_ of things are changing quite quickly, and I don't think this will continue for too long.

I think overall it's definitely better to keep all of the code in this package.

**Comment by theogf** [comment]
That's fair. My second worry was that if we keep adding kernels, the load up could start to be heavy...
