### ISSUE TITLE
kappa vs _kernel vs k(x, y)

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#87]
Related to #72 but more general.

### kappa

`kappa` can do one of several things, depending on context

1. if you can write the kernel as a function of the distance between two points (as in the so-called `SimpleKernel` case, `kappa` should do the rest of the computation. eg. for an EQ kernel, `kappa(k, d^2) = exp(-d^2 / 2)`.
2. if two inputs are provided and they're `Vector` or `Real`, treat them as single inputs and return a scalar that is the kernel evaluated at those inputs
3. if the inputs are matrices, compute `kernelmatrix`.

### `_kernel`

I'm really not sure what this does, and seems to be implemented only sporadically. I think it maybe computes the kernel for particular inputs, but I'm not really sure.

### `k(x, y)`

same as `kappa`, but without the `SimpleKernel` bit.

## Issue with the current situation

There are multiple ways to do the same thing, and `kappa` means different things depending upon the input types. This is bad, as it's confusing for new users. The best situation is that there is one, and only one, way to do things. This minimises the amount that users and developers have to learn to work with / develop the package. If they wish to have aliases, they should implement them themselves in their own code.

## Proposal

1. Completely remove `_kernel`. I don't think there will be much objection to this given #72
2. Remove all binary methods of `kappa`, so that only the unary method exists, and only for `SimpleKernel`s.
3. Change `k(x, y)` such that it only ever tries to evaluate the kernel at a pair of inputs (returns a scalar). It will never return a matrix.

With these changes, `kernelmatrix` / `kernelmatrix!` will become the sole way to compute the kernel matrix associated with a data set.

@theogf @devmotion what are your thoughts?

**Comment by devmotion** [comment]
I completely agree and very much in favour of the proposed changes.

**Comment by theogf** [comment]
I also fully agree with the proposal.
I am solving 1. with #83
2. and 3. Could be done in another PR

**Comment by willtebbutt** [comment]
Great, will make a PR

**Comment by devmotion** [comment]
Was fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/95.
