### ISSUE TITLE
Implement test suite for custom kernels

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#88]
How about we add a testing interface for users to check if their custom kernel satisfy all the conditions.
As described in this blog post : https://white.ucc.asn.au/2020/04/19/Julia-Antipatterns.html (see Aside: Test Suites, for interface testing.)
We can then define one for `SimpleKernel` and `BaseKernel`

**Comment by willtebbutt** [comment]
I've done this extensively in Stheno. I've started work on a port for KernelFunctions, but it would be better if we had #43 and #87 resolved before sorting this to minimise work.
