### ISSUE TITLE
Support for matrix valued inputs

### ISSUE THREAD

**Issue by niklasschmitz** [JuliaGaussianProcesses/KernelFunctions.jl#9]
I really like the simple interface of this package. But what is the best way to handle samples that naturally come with more array-dimensions than 1 (e.g. matrices)? So far there is support for scalar and vectorial inputs.

Say we have M joint observations of N points with D coordinates each
```julia
M, N, D  = 10, 5, 3
X = rand(M, N, D)
k = SomeKernel()
K = kernelmatrix(k, X)
```
where `SomeKernel` is a custom kernel that can compare two (N,D) matrices and return a scalar. To my understanding this is not supported yet by `kernelmatrix`, as it expects `X` to be of type `AbstractMatrix` (which is `AbstractArray{T,2}` ) but in the shown case we have
`typeof(X) == Array{Float64,3}`

What are your thoughts: Should there be a dispatch for that? Or should all samples be vectorized and then let the kernel function de-vectorize them again?

**Comment by IsakFalk** [comment]
I have a similar problem as I'd like to calculate kernels over distributions which in practice reduces to kernels over empirical datasets (where in the example above M represents the number of distributions, N the number of samples from each distribution and D the dimensionality of each sample if we assume them to be the same). Interested to see the response to this.

**Comment by theogf** [comment]
The goal of the package is indeed to be able to treat all kind of inputs.
So far I only implemented the specialization for vectors/scalars but it is possible but I will create a PR to solve this. However I need to know what metric would you use to compute the initial distance between your set of points.
For example for vectors it can be `SqEuclidean`,`LinearProduct` etc...

**Comment by theogf** [comment]
Oh @IsakFalk  I just realized you gave a couple of links in #10

**Comment by theogf** [comment]
For distributions is it this approach you would like to see implemented ?
https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions#Kernel_two-sample_test

**Comment by IsakFalk** [comment]
@theogf Yes, that is the way to do it. The MMD is a way to compare distributions to each other, but it can also be used to not used measure distances between distributions, but also define kernels on the space of distributions defined on some domain X directly (by simply doing K(p, q) = exp(-\rho^2 MMD(p, q)).

**Comment by IsakFalk** [comment]
I've opened an issue over at the Distances.jl, https://github.com/JuliaStats/Distances.jl/issues/154#issue-535459387, library about implementing MMD there, in that case we could use it to easily implement kernels over distributions (at least when the distributions is a convex combination of dirac deltas!).

**Comment by niklasschmitz** [comment]
So this got also solved by the move to the generic `AbstractVector` datasets for `kernelmatrix`. Nice to learn about Julia's pairwise broadcasting mechanisms  with`κ.(x, permutedims(y))`!
