### ISSUE TITLE
Remove `_kernelmatrix`

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#91]
`_kernelmatrix` appears only once, so just remove it?

_Originally posted by @devmotion in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/83_

**Comment by willtebbutt** [comment]
I'll address this when sorting out #87

**Comment by theogf** [comment]
I ended up removing it in #83

**Comment by willtebbutt** [comment]
Great!

**Comment by theogf** [comment]
Solved with #83
