### ISSUE TITLE
LowRankTransform

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#97]
This isn't the best name, as it doesn't have to map from high to low dimensions. A better name might just be `LinearTransform`.

**Comment by theogf** [comment]
Wouldn't linear transform imply adding a bias as well (AX + b). I know that the exact name for this would be affine but people use linear implicitly for it

**Comment by willtebbutt** [comment]
Do they? I wasn't aware that that's a thing that people do 😬 . In any case, I'm not sure it's a good reason not to use the name linear transform for a thing that is quite clearly a linear transform. I would be fine also having an affine transform 🤷‍♂️ . Or just having an affine transform with a linear transform being a special case.

**Comment by theogf** [comment]
Well we mostly hear about linear regression not affine regression :D 
But anyway you're right. Linear transform is more adapted.
